"project_id": "587337"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

"files": [
        {
            "source": "/VocaDbWeb/public/locales/en/*.json", #source files filter
            "translation": "/VocaDbWeb/public/locales/%two_letters_code%/%original_file_name%", #where translations are stored
        },
    ]

